config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'toppages#index'
  resources :postships, only: %i[create destroy]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :favorites, only: %i[create destroy]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: %i[show create new index edit update] do
    member do
      get :followings
      get :followers
      get :liked_books
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :relationships, only: %i[create destroy]
  get 'search', to: 'books#new'
  get 'books/:id', to: 'books#show', as: :book do
    member do
      get :liked_users
    end
  end

  resources :posts, only: %i[new create destroy show edit update]
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/favorites_controller.rb
# frozen_string_literal: true

class FavoritesController < ApplicationController
  before_action :require_user_logged_in
  def create
    @book = Book.find_or_initialize_by(isbn: params[:book_isbn])
    unless @book.persisted?
      results = RakutenWebService::Books::Book.search(isbn: @book.isbn)
      @book = Book.new(read(results.first))
      @book.save
    end
    current_user.like(@book)
    flash[:success] = 'お気に入りに登録しました'
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @book = Book.find(params[:book_id])
    current_user.unlike(@book)
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/favorites_helper.rb
# frozen_string_literal: true

module FavoritesHelper
end

app/views/favorites/_like_button.html.erb
<% book = Book.find_by(isbn: book.isbn) || book %>
<% if current_user.like?(book) %>
  <%= form_tag(favorite_path(book.id), method: :delete) do %>
    <%= hidden_field_tag :book_id, book.id %>
    <%= submit_tag 'like済み',class:"btn btn-danger" %>
  <% end %>
<% else %>
  <%= form_tag(favorites_path) do %>
    <%= hidden_field_tag :book_isbn, book.isbn %>
    <%= submit_tag 'likeする',class:"btn btn-success" %>
  <% end %>
<% end %>