config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'toppages#index'
  resources :postships, only: %i[create destroy]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :favorites, only: %i[create destroy]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: %i[show create new index edit update] do
    member do
      get :followings
      get :followers
      get :liked_books
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :relationships, only: %i[create destroy]
  get 'search', to: 'books#new'
  get 'books/:id', to: 'books#show', as: :book do
    member do
      get :liked_users
    end
  end

  resources :posts, only: %i[new create destroy show edit update]
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: { case_sensitive: false }
  # validates :password , format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,100}+\z/i }
  has_secure_password

  validates :bio, length: { maximum: 150 }

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reversed_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reversed_of_relationship, source: :user

  has_many :books, through: :favorites

  has_many :favorites
  has_many :liked_books, through: :favorites, source: :book

  has_many :posts

  has_many :postships, dependent: :destroy
  has_many :like_posts, through: :postships, source: :post

  def post_like(post)
    postships.find_or_create_by(post_id: post.id)
  end

  def post_unlike(post)
    postship = postships.find_by(post_id: post.id)
    postship&.destroy
  end

  def post_liked?(post)
    like_posts.include?(post)
  end

  def follow(other_user)
    relationships.find_or_create_by(follow_id: other_user.id) unless self == other_user
  end

  def unfollow(other_user)
    relationship = relationships.find_by(follow_id: other_user.id)
    relationship&.destroy
  end

  def following?(other_user)
    followings.include?(other_user)
  end

  def like(book)
    favorites.find_or_create_by(book_id: book.id)
  end

  def unlike(book)
    favorite = favorites.find_by(book_id: book.id)
    favorite&.destroy
  end

  def like?(book)
    liked_books.include?(book)
  end

  def feed_posts
    Post.where(user_id: following_ids + [id])
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show]
  def show
    @user = User.find(params[:id])
    count_users(@user)
    @posts = @user.posts.order('created_at DESC').page(params[:page])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def new
    @user = User.new
  end

  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    count_users(@user)
  end

  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    count_users(@user)
  end

  def liked_books
    @user = User.find(params[:id])
    @liked_books = @user.liked_books.page(params[:page])
    count_users(@user)
  end

  def index
    @users = []
    @name = params[:name]
    if @name
      results = User.where(
        name: @name
      )
      results.each do |result|
        user = User.find_or_initialize_by(read(result))
        @users << user
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'ユーザー情報が編集されました'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザー情報の保存に失敗しました'
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :birthday, :bio, :password_confirmation)
  end

  def read(result)
    name = result['name']
    {
      name: name
    }
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_user_aside.html.erb
<aside class="col-md-3">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @user.name %></h3>
    </div>
    <div class="panel-body">
      <img src="/images/human.jpg" width="100%" height="100%" alt="" class="img-circle">
    </div> 
  </div>
  <p>生年月日：<%= @user.birthday %></p>
  <p><%= @user.bio %></p>
  <%= render 'relationships/follow_button', user: @user %>
  <% if current_user == @user %>
    <%= link_to '編集',edit_user_path(@user),class:"btn btn-success btn-block btn-edit" %>
  <% end %>
  <a href="https://twitter.com/<%= @user.twitter_id %>" target="_blank"><img src="../images/Twitter_Logo_Blue.png" width="90px" height="90px"></a>
</aside>

app/views/users/_user_info_switch.html.erb
<ul class="nav nav-tabs nav-justified">
  <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>投稿 <span class="badge"><%= @count_posts %></span><% end %></li>
  <li class="<%= 'active' if current_page?(liked_books_user_path(@user)) %>"><%= link_to liked_books_user_path(@user) do %>いいねした本 <span class="badge"><%= @count_liked_books %></span><% end %></li>
  <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>Followings <span class="badge"><%= @count_followings %></span><% end %></li>
  <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>Followers <span class="badge"><%= @count_followers %></span><% end %></li>
</ul>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="media-list">
    <% users.each do |user| %>
      <li class="media">
        <div class="media-left">
          <img src="/images/human.jpg" width="80" height="80" alt="" class="img-circle">
        </div>
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%#= paginate users %>
<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <h1>ユーザー情報編集ページ</h1>
    <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div class="alert alert-warning">
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>    
      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class:'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :bio, '自己紹介' %>
        <%= f.text_area :bio, class:'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :twitter_id, 'Twitter' %>
        <%= f.text_field :twitter_id, class:'form-control' %>
      <div class="form-group">
        <%#= f.label :password, 'パスワード' %>
        <%#= f.password_field :password, class:'form-control' %>
      </div>
      <div class="form-group">
        <%#= f.label :password_confirmation, 'パスワード（確認）' %>
        <%#= f.password_field :password_confirmation, class:'form-control' %>
      </div>
      <%= f.submit '編集完了', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<% title_variable "#{@user.name} さん | フォローされている人" %>
<div class="row">
  <%= render 'user_aside' %>
  <div class="col-md-9 col-xs-12">
    <%= render 'user_info_switch' %>
    <%= render 'users', users: @followers %>
  </div>
</div>

app/views/users/followings.html.erb
<% title_variable "#{@user.name} さん | フォローしている人" %>
<div class="row">
  <%= render 'user_aside' %>
  <div class="col-md-9 col-xs-12">
    <%= render 'user_info_switch' %>
    <%= render 'users', users: @followings %>
  </div>
</div>

app/views/users/index.html.erb
<% title_variable "#{@name} のユーザー検索結果" %>
<%= render 'users', users: @users %>

app/views/users/liked_books.html.erb
<% title_variable "#{@user.name} さん | いいねした本" %>
<div class="row">
  <%= render 'user_aside' %>
  <div class="col-md-9 col-xs-12">
    <%= render 'user_info_switch' %>
    <%= render 'books/user_page_books', books: @liked_books %>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-offset-3 col-md-6 col-xs-12">
    <div class="panel panel-default">
      <div class="panel-heading">会員登録</div>
      <div class="panel-body">
        <%= form_for(@user) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
          <div class="form-group">
            <%= f.label :name, 'お名前' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :birthday, '生年月日' %><br>
            <%= f.date_select(
              :birthday,
              :use_month_numbers => true,
              
              start_year: 1900,
              end_year:   (Time.now.year),
              default:    Date.new(2002, 3, 26)) %>
          </div>

          <div class="form-group">
            <%= f.label :email, 'メールアドレス' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード（確認）' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <div class="text-right">
            <%= f.submit '登録する', class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% title_variable "#{@user.name} さん | プロフィール" %>
<div class="row">
  <%= render 'user_aside' %>
  <div class="col-md-9 col-xs-12">
    <%= render 'user_info_switch' %>
    <%= render 'posts/posts', posts: @posts %>
  </div>
</div>