config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'toppages#index'
  resources :postships, only: %i[create destroy]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :favorites, only: %i[create destroy]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: %i[show create new index edit update] do
    member do
      get :followings
      get :followers
      get :liked_books
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :relationships, only: %i[create destroy]
  get 'search', to: 'books#new'
  get 'books/:id', to: 'books#show', as: :book do
    member do
      get :liked_users
    end
  end

  resources :posts, only: %i[new create destroy show edit update]
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true, length: { maximum: 255 }
  validates :book, presence: true
  has_many :postships
  has_many :liked_users, through: :postships, source: :user
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :require_user_logged_in
  def create
    @book = Book.find(params[:book_id])
    @book.save

    @post = current_user.posts.new(post_params)
    @post.book_id = @book.id
    if @post.save
      flash[:success] = '投稿が送信されました'
      redirect_to @post
    else
      flash[:danger] = '投稿の送信に失敗しました'
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:success] = '投稿が削除されました'
    redirect_back(fallback_location: root_path)
  end

  def new
    @book = Book.find_or_initialize_by(isbn: params[:book_isbn])
    unless @book.persisted?
      results = RakutenWebService::Books::Book.search(isbn: @book.isbn)
      @book = Book.new(read(results.first))
      @book.save
    end
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
    @book = Book.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @book = Book.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      flash.now[:danger] = '投稿の保存に失敗しました'
      render :edit
    end
  end

  private

  def post_params
    params.require(:post).permit(:comment, :book)
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/posts/_new_post_button.html.erb
<%= link_to '投稿する',new_post_path(book_isbn: book.isbn), class:"btn btn-success" %>

app/views/posts/_posts.html.erb
<ul class="media-list">
  <% @posts.each do |post| %>
    <li class="media">
      <div class="media-left">
        <img src="/images/human.jpg" width="80" height="80" alt="" class="img-circle">
      </div>
      <div class="media-body">
        <div>
          <%= link_to post.user.name, user_path(post.user) %><span class="text-muted">&nbsp;posted at&nbsp;<%= post.created_at %></span>
          <h4><img src="http://freeiconbox.com/icon/256/32354.png" width="33" height="33"><%= link_to post.book.title, post.book %></h4>
          <p><%= simple_format(post.comment) %> </p>
        </div>
        <div class="toko">
          <% if current_user.post_liked?(post) %>
            <%= form_for(current_user.postships.find_by(post_id: post.id), html: { method: :delete },class: 'new_postships') do |f| %>
              <%= hidden_field_tag :post_id, post.id %>
              <%= button_tag "", id: "heart" %><%= post.liked_users.count %>
            <% end %>
          <% else %>
            <%= form_for(current_user.postships.build) do |f| %>
              <%= hidden_field_tag :post_id, post.id %>
              <%= button_tag "", id: "heart-empty" %> <%= post.liked_users.count %>
            <% end %>
          <% end %>      
        </div>
        <div class="toko">
          <%= link_to '投稿詳細へ',post,class: 'btn btn-danger btn-xs' %>
        </div>
        <div class="toko">
          <% if current_user == post.user %>
            <%= link_to "Delete", post ,method: :delete,data:{confirm:"本当に削除しますか？" },class: 'btn btn-danger btn-xs' %>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-md-offset-3 col-md-6 col-xs-12">
    <%= form_for(@post) do |f| %>
      <% if @post.errors.any? %>
        <div class="alert alert-warning">
          <ul>
            <% @post.errors.full_messages.each do |message| %>
            w  <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>   
      <div class="book_info">
        <h3>Book情報</h3>
        <%= @book.title %>
        <%= hidden_field_tag :book_id, @book.id %>
      </div>
　　　<br>
      <div class="form-group">
        <h3>コメント</h3>
        <%= f.text_area :comment, class: 'form-control',:size => "10x8" %>
      </div>
      <%= f.submit '投稿', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="row">
  <h1>メッセージ詳細ページ</h1>
  <h2>投稿情報</h2>
  <br>
  <div>
    投稿日時：<%= @post.created_at %>
    <%= simple_format(@post.comment) %>
    <%= link_to 'このメッセージを編集する', edit_post_path(@post),  class: 'btn btn-danger' %>
  </ul>
  </div>
  <h2>書籍情報</h2><br>
  <ul class="media-list">
    <li class="media">
      <div class="media-left">
        <img src="<%= @post.book.image_url %>" height="120" width="85" alt="">
      </div>
      <div class="media-body">
        <h4>    
          <%= link_to @post.book.title,@post.book %>
        </h4>
        <div>
          著者：<%= @post.book.author %>
        </div>
        <div>
          価格：<%= @post.book.item_price %>円
        </div>
        <div>
          発売日：<%= @post.book.sales_date %>
        </div>
      </div>
    </li>
</div>