config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'toppages#index'
  resources :postships, only: %i[create destroy]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :favorites, only: %i[create destroy]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: %i[show create new index edit update] do
    member do
      get :followings
      get :followers
      get :liked_books
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :relationships, only: %i[create destroy]
  get 'search', to: 'books#new'
  get 'books/:id', to: 'books#show', as: :book do
    member do
      get :liked_users
    end
  end

  resources :posts, only: %i[new create destroy show edit update]
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <ul class="list-inline text-center">
    <li class="footer-list"><%= link_to "プライバシーポリシー",page_path("policy") %></li>
    <li class="footer-list"><%= link_to "利用規約",page_path("rules") %></li>
    <li class="footer-list"><a href="https://twitter.com/_hibinokota_" target="_blank">お問い合わせ</a></li>
    <li class="footer-list"><a href="http://pltn-18.sakura.ne.jp/" target="_blank">運営者情報</a></li>
    <li class="footer-list"><a href="https://github.com/2002hbnsn/doc-doc" target="_blank">ソースコード</a></li>
  </ul>
  <div class="text-center text-muted">© 2018 doc-doc</div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-left" href="/"><img src="/images/logo.png" alt="Monolist"></a>
    </div> 
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if logged_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <span class="gravatar">
                <img src="images/human.jpg" width="25" height="25" alt="" class="img-circle">
              </span>
              <%= current_user.name %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to 'マイページ', user_path(current_user) %>
              </li>
              <li role="separator" class="divider"></li>
              <li>
                <%= link_to 'ログアウト', logout_path,method: :delete %>
              </li>
            </ul>
          </li>
        </ul>
        <%= form_tag(search_path, method: :get,class: "navbar-form navbar-right") do %>
          <div class="form-group">
            <%= text_field_tag :title, @title, class: 'form-control input-lg', placeholder: "本を検索", size: 30 %>
          </div>
          <%= submit_tag '検索', class: 'btn btn-success btn-lg' %>
        <% end %>  
        <%= form_tag(users_path, method: :get,class: "navbar-form navbar-right") do %>
          <div class="form-group">
            <%= text_field_tag :name, @name, class: 'form-control input-lg', placeholder: "ユーザーを検索", size: 30 %>
          </div>
          <%= submit_tag '検索', class: 'btn btn-success btn-lg' %>
        <% end %>  
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to '新規登録', signup_path %></li>
            <li><%= link_to 'ログイン', login_path %></li>
          </ul>
          <%= form_tag(search_path, method: :get,class: "navbar-form navbar-right") do %>
            <div class="form-group">
              <%= text_field_tag :title, @title, class: 'form-control input-lg', placeholder: "本を検索", size: 30 %>
            </div>
            <%= submit_tag '検索', class: 'btn btn-success btn-lg' %>
          <% end %>  
          <%= form_tag(users_path, method: :get,class: "navbar-form navbar-right") do %>
            <div class="form-group">
              <%= text_field_tag :name, @name, class: 'form-control input-lg', placeholder: "ユーザーを検索", size: 30 %>
            </div>
            <%= submit_tag '検索', class: 'btn btn-success btn-lg' %>
          <% end %>  
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= title %></title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'layouts/navbar' %>
    <%= yield :cover %>
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>